#!/usr/bin/env bash

SESSION_FOLDER="$(mktemp --directory)"
script --timing="$SESSION_FOLDER/session.timing" "$SESSION_FOLDER/session.data" -q

if [[ -z "$1" ]]; then
    SESSION_ARCHIVE="$(mktemp -u session-XXXXX.zip)"
else
    SESSION_ARCHIVE="$1.zip"
fi

cd "$SESSION_FOLDER"
zip -9r "$SESSION_FOLDER/$SESSION_ARCHIVE" * -q
cd -
mv "$SESSION_FOLDER/$SESSION_ARCHIVE" .
echo "Your session record created at \"$SESSION_ARCHIVE\"."
rm -rf "$SESSION_FOLDER"
