#!/usr/bin/env bash

SESSION_REPLAY_DIR="$(mktemp --directory -u)"
unzip "$1" -d "$SESSION_REPLAY_DIR" -q
scriptreplay -t "$SESSION_REPLAY_DIR"/session.timing "$SESSION_REPLAY_DIR"/session.data
rm -rf "$SESSION_REPLAY_DIR"

